services:
  matching-service:
    image: peerprep/matching-service:test
    ports:
    - "3000:3000"
    build: ./matching-service
    profiles:
      - local
  collab-service:
    depends_on:
      - matching-service
    image: peerprep/collab-service:test
    ports: 
    - "8081:8081"
    build: ./collab-service
    profiles:
      - deploy
      - local
  question-service:
    image: peerprep/question-service:test
    ports:
    - "3005:3005"
    build: ./question-service
    profiles:
      - deploy
      - local