name: CD

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ feat/ci, main ]

jobs:
  deploy_matching_service:
    # Define environment (Below secrets are only defined in the environment and not globally)
    environment: cs3219-team-26
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Change directory to matching-service
        run: |
          cd matching-service

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ryantanlien99/peerprep:matching-service

  deploy_firebase:
    # Define environment (Below secrets are only defined in the environment and not globally)
    environment: cs3219-team-26

    # Define environment variables
    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      PROJECT_PATH: ./user-service

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Cd to user-service
    - name: Change directory to user-service
      run: |
        cd user-service
        npm install

    # Deploy user-service
    - name:  Deploy user-service to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions

