name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feat/ci , firebase-testing ]

jobs:
  build:
  
    # Define environment (Below secrets are only defined in the environment and not globally)
    environment: cs3219-team-26

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    # Run npm install and npm test on matching-service
    - name: Build and test matching-service
      run: |
        cd matching-service
        pwd
        touch .env
        echo 'AWS_DB=${{secrets.AWS_DB}}' >> .env
        echo 'AWS_DB_USER=${{secrets.AWS_DB_USER}}' >> .env
        echo 'AWS_DB_PASSWORD=${{secrets.AWS_DB_PASSWORD}}' >> .env
        echo 'AWS_DB_ENDPOINT=${{secrets.AWS_DB_ENDPOINT}}' >> .env
        echo 'AWS_DB_PORT=${{secrets.AWS_DB_PORT}}' >> .env
        echo 'AWS_SOCKET_DB=${{secrets.AWS_SOCKET_DB}}' >> .env
        echo 'AWS_SOCKET_DB_USER=${{secrets.AWS_SOCKET_DB_USER}}' >> .env
        echo 'AWS_SOCKET_DB_PASSWORD=${{secrets.AWS_SOCKET_DB_PASSWORD}}' >> .env
        echo 'AWS_SOCKET_DB_ENDPOINT=${{secrets.AWS_SOCKET_DB_ENDPOINT}}' >> .env
        echo 'AWS_SOCKET_DB_PORT=${{secrets.AWS_SOCKET_DB_PORT}}' >> .env
        cat .env
        npm install
        npm test
        cd ..
    - name: Change directory to user-service
      run: |
        cd user-service
    # Run npm install and npm test on user-service
    - name: create ServiceAccountKey.json
      uses: schdck/create-env-json@v1
      with:
        file-name: 'ServiceAccountKey.json'
        type: 'service-account'
        project_id: 'peerprep-userser'
        private_key_id:  ${{ secrets.PRIVATE_KEY_ID }}
        private_key:  ${{ secrets.PRIVATE_KEY }}
        client_email: 'peerprep-userser@appspot.gserviceaccount.com'
        auth_uri": 'https://accounts.google.com/o/oauth2/auth'
        token_uri: 'https://oauth2.googleapis.com/token'
        client_id: ${{ secrets.CLIENT_ID }}
        auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs'
        client_x509_cert_url: 'https://www.googleapis.com/robot/v1/metadata/x509/peerprep-userser%40appspot.gserviceaccount.com'
    
    - name: Build and test user-service
      run: |
        touch .env
        echo 'FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}' >> .env
        cat ServiceAccountKey.json
        cat .env
        pwd
        npm install
        # npm run firebase
        npm test
        cd ..
    - name: Setup firebase emulator
      uses: w9jds/firebase-action@master
      with:
        args: emulators:start && npm test"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      